#!/bin/bash
function printWithColor {
	green='\e[0;32m'
	NC='\e[0m' # No Color
	echo -e "${green}$1${NC}"
}
echo "Git fetch all submodule updates"
git pull
echo "Git fetch all submodule updates"
git submodule foreach git pull origin master
echo "Git commit the updates"
git commit -am "Updated submodules"
echo "Git push the updates"
git push

